name: CI

on:
  push:
    branches: [master, fb]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node_version: [ '14', '16' ]

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Semantic Release
        run: yarn semver
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
